export const ADD_NEW_MESSAGE = "CHAT/ADD_NEW_MESSAGE";
export const DELETE_MESSAGE = "CHAT/DELETE_MESSAGE";
export const FETCHED_MESSAGES = "CHAT/FETCHED_MESSAGES";
export const SHOW_EDIT = "CHAT/SHOW_EDIT";
export const HIDE_EDIT = "CHAT/HIDE_EDIT";
export const EDIT_MESSAGE = "CHAT/EDIT_MESSAGE";


export const CHANGE_HEADER_DATA = "HEADER/CHANGE_HEADER_DATA";